// Bulk-import company sources from public new-grad/internship listings (SimplifyJobs).
// Parses each posting's apply URL into a {company, ats, slug} board on a supported
// single-GET ATS (greenhouse / lever / ashby / smartrecruiters), ranks by how many
// postings each board has (a proxy for how actively it hires), excludes boards already
// in the curated sources.yaml, and writes the top N to sources.generated.yaml — which
// loadSources() merges. Workday is skipped in bulk (paginated/slow); add those by hand.
//
//   pnpm tsx scripts/import-sources.ts [limit]     # default limit 500
import '../src/env';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { dump } from 'js-yaml';
import { loadSources } from '../src/config/sources';
import type { Ats } from '../src/types';

const LIMIT = Number(process.argv[2] ?? 500);
const LISTINGS = [
  'https://raw.githubusercontent.com/SimplifyJobs/New-Grad-Positions/dev/.github/scripts/listings.json',
  'https://raw.githubusercontent.com/SimplifyJobs/Summer2026-Internships/dev/.github/scripts/listings.json',
];

// Parse an apply URL into a single-GET ATS board. Returns null for unsupported hosts
// (workday/icims/custom) or unparseable slugs.
function parseApplyUrl(rawUrl: string): { ats: Ats; slug: string } | null {
  let u: URL;
  try {
    u = new URL(rawUrl);
  } catch {
    return null;
  }
  const host = u.hostname.toLowerCase();
  const seg = u.pathname.split('/').filter(Boolean);
  const ok = (s: string | undefined): s is string => !!s && /^[A-Za-z0-9][A-Za-z0-9_-]{1,59}$/.test(s);

  if (host.endsWith('greenhouse.io')) {
    if (seg[0] === 'embed') {
      const forSlug = u.searchParams.get('for') ?? undefined;
      return ok(forSlug) ? { ats: 'greenhouse', slug: forSlug } : null;
    }
    return ok(seg[0]) ? { ats: 'greenhouse', slug: seg[0]! } : null;
  }
  if (host.endsWith('lever.co')) return ok(seg[0]) ? { ats: 'lever', slug: seg[0]! } : null;
  if (host.endsWith('ashbyhq.com')) return ok(seg[0]) ? { ats: 'ashby', slug: seg[0]! } : null;
  if (host.endsWith('smartrecruiters.com')) {
    // jobs.smartrecruiters.com/{companyId}/{postingId}
    const slug = seg[0] === 'companies' ? seg[1] : seg[0];
    return ok(slug) ? { ats: 'smartrecruiters', slug: slug! } : null;
  }
  return null;
}

interface Board {
  ats: Ats;
  slug: string;
  company: string;
  count: number;
}

async function main() {
  // Existing curated boards to exclude (load curated file only, not the generated one).
  const curated = loadSources(path.resolve('sources.yaml'));
  const curatedKeys = new Set(curated.map((s) => `${s.ats}:${s.slug}`));

  const boards = new Map<string, Board>();
  let listingsSeen = 0;
  for (const url of LISTINGS) {
    const res = await fetch(url, { headers: { 'User-Agent': 'sift-import' } });
    if (!res.ok) {
      console.warn(`  skip ${url} (HTTP ${res.status})`);
      continue;
    }
    const data = (await res.json()) as Array<{
      company_name?: string;
      url?: string;
      active?: boolean;
    }>;
    for (const e of data) {
      listingsSeen++;
      if (e.active === false || !e.url) continue;
      const parsed = parseApplyUrl(e.url);
      if (!parsed) continue;
      const key = `${parsed.ats}:${parsed.slug}`;
      if (curatedKeys.has(key)) continue;
      const existing = boards.get(key);
      if (existing) existing.count++;
      else boards.set(key, { ...parsed, company: (e.company_name ?? parsed.slug).trim(), count: 1 });
    }
  }

  const ranked = [...boards.values()].sort((a, b) => b.count - a.count);
  const picked = ranked.slice(0, LIMIT);

  const byAts: Record<string, number> = {};
  for (const b of picked) byAts[b.ats] = (byAts[b.ats] ?? 0) + 1;

  const yaml = picked.map((b) => ({ company: b.company, ats: b.ats, slug: b.slug, tier: 3, tags: [] }));
  const header =
    '# GENERATED by scripts/import-sources.ts — do not hand-edit.\n' +
    `# ${picked.length} bulk boards imported from SimplifyJobs new-grad + internship listings,\n` +
    '# ranked by posting volume. Curated sources.yaml wins on any conflict.\n\n';
  const outPath = path.resolve('sources.generated.yaml');
  writeFileSync(outPath, header + dump(yaml, { lineWidth: 120 }), 'utf8');

  console.log(`listings scanned: ${listingsSeen}`);
  console.log(`unique new supported boards found: ${boards.size}`);
  console.log(`wrote ${picked.length} (limit ${LIMIT}) to sources.generated.yaml`);
  console.log('by ats:', JSON.stringify(byAts));
  console.log('top 10:', picked.slice(0, 10).map((b) => `${b.company}(${b.ats}, ${b.count})`).join(', '));
}

main();
